
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask_app
    restart: always
    command: python run.py
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - ./instance:/app/instance
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: redis_server
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery_worker
    restart: always
    command: celery -A app.tasks.celery_worker.celery worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - web
      - redis

  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery_beat
    restart: always
    command: celery -A app.tasks.celery_worker.celery beat --loglevel=info --schedule=/tmp/celerybeat-schedule
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - web
      - redis

volumes:
  redis_data: